=== Gelotto/ArchX-Wallet-Dapps/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Name of the Dapp"
    },
    "description": {
      "type": "string",
      "description": "Description of the Dapp"
    },
    "dappImages": {
      "type": "object",
      "properties": {
        "dappBanner": {
          "type": "string",
          "description": "Filename of the Dapp banner image located in the same folder"
        },
        "dappLogo": {
          "type": "string",
          "description": "Filename of the Dapp logo image located in the same folder"
        }
      },
      "required": ["dappBanner", "dappLogo"],
      "description": "Filenames of the Dapp banner and logo images located in the same folder as the JSON file"
    },
    "websiteUrl": {
      "type": "object",
      "properties": {
        "mainnet": {
          "type": "string",
          "format": "uri",
          "description": "URL of the Dapp on the mainnet"
        },
        "testnet": {
          "type": "string",
          "format": "uri",
          "description": "URL of the Dapp on the testnet"
        }
      },
      "required": ["mainnet", "testnet"],
      "description": "Website URLs for the Dapp on mainnet and testnet"
    },
    "category": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "DeFi-Lending & Borrowing",
          "DeFi-Decentralized Exchanges (DEX)",
          "DeFi-Yield Farming",
          "DeFi-Liquid Staking",
          "DeFi-Insurance",
          "NFT-Collectibles",
          "NFT-Virtual Real Estate",
          "NFT-Domain Names",
          "NFT-Music",
          "NFT-Sports & Gaming",
          "Social-Decentralized Social Networks",
          "Social-Content Creation & Monetization",
          "Social-Messaging & Communication",
          "Social-Decentralized Autonomous Organizations (DAO)",
          "Infrastructure-Oracle Providers",
          "Infrastructure-Interoperability & Cross-Chain",
          "Infrastructure-Data Storage",
          "Infrastructure-Identity & Authentication",
          "Privacy-Privacy-preserving Technologies",
          "Privacy-Private Transactions",
          "Tools & Utilities-Wallets",
          "Tools & Utilities-Analytics & Tracking",
          "Tools & Utilities-Developer Tools",
          "Tools & Utilities-Governance",
          "Unknown"
        ]
      },
      "description": "Categories of the Dapp"
    },
    "privacyPolicyUrl": {
      "type": "string",
      "format": "uri",
      "description": "URL of the Privacy Policy"
    },
    "termsOfServiceUrl": {
      "type": "string",
      "format": "uri",
      "description": "URL of the Terms of Service"
    },
    "githubUrl": {
      "type": "string",
      "format": "uri",
      "description": "URL of the Dapp's GitHub repository"
    },
    "contactEmail": {
      "type": "string",
      "format": "email",
      "description": "Contact email for the Dapp"
    },
    "smartContractAddresses": {
      "type": "object",
      "properties": {
        "mainnet": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "testnet": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "description": "Smart contract addresses for the Dapp on mainnet and testnet"
    },
    "enabled": {
      "type": "boolean",
      "description": "Flag to indicate whether the Dapp should be enabled or disabled in the wallet Dapp browser."
    }
  },
  "required": ["name", "description", "dappImages", "websiteUrl", "category", "enabled"],
  "description": "Schema for Dapp details"
}

=== Gelotto/ArchX-Wallet-Dapps/Archway-Dapps/BonusBlock/details.json
{
  "name": "BonusBlock",
  "description": "BonusBlock is an engagement protocol that assists any Web3 project in making their present product more actionable and successful by incorporating tailored features and an on-chain referral system. Users receive different benefits for participating in these engagement programmes. Sign up now to begin your journey!",
  "dappImages": {
    "dappBanner": "bonusblock-banner.png",
    "dappLogo": "bonusblock-logo.png"
  },
  "websiteUrl": {
    "mainnet": "https://archway.bonusblock.io/",
    "testnet": "https://archway-dev.bonusblock.io/"
  },
  "category": ["Tools & Utilities-Developer Tools"],
  "enabled": true
}

=== Gelotto/ArchX-Wallet-Dapps/Archway-Dapps/ArchID/details.json
{
  "name": "ArchID",
  "description": "ArchID is a name service for Archway Network, supporting domains, subdomains, and web2 identity verification. Mint domains as NFTs and update their metadata to share your social accounts, and personal flair, with the Archway eco-system. Developers can add Github repositories and smart contract addresses as subdomains managed by their main address. ArchID re-imagines blockchain identity as a system built for developers by developers, powered by updatable NFTs managed by the core ArchID protocol. Gone are the days of static, unchanging tokens, welcome to the new era of NFT assets that grow and develop alongside you as your dapps mature.",
  "dappImages": {
    "dappBanner": "archid-banner.png",
    "dappLogo": "archid-logo.png"
  },
  "websiteUrl": {
    "mainnet": "https://archid.app/",
    "testnet": "https://test.archid.app/"
  },
  "category": ["NFT-Domain Names"],
  "privacyPolicyUrl": "https://archid.app/policy.html",
  "termsOfServiceUrl": "https://archid.app/tos.html",
  "githubUrl": "https://github.com/archid-protocol",
  "contactEmail": "archid.protocol@gmail.com",
  "smartContractAddresses": {
    "mainnet": [],
    "testnet": [
      "archway1lr8rstt40s697hqpedv2nvt27f4cuccqwvly9gnvuszxmcevrlns60xw4r",
      "archway146htsfvftmq8fl26977w9xgdwmsptr2quuf7yyra4j0gttx32z3secq008"
    ]
  },
  "enabled": true
}

=== Gelotto/ArchX-Wallet-Dapps/Example-Dapp/details.json
{
  "name": "SampleDex",
  "description": "SampleDex is a decentralized exchange for trading Cosmos-based tokens.",
  "dappImages": {
    "dappBanner": "sampledex-banner.png",
    "dappLogo": "sampledex-logo.png"
  },
  "websiteUrl": {
    "mainnet": "https://sampledex.com",
    "testnet": "https://testnet.sampledex.com"
  },
  "category": ["DeFi-Decentralized Exchanges (DEX)"],
  "privacyPolicyUrl": "https://sampledex.com/privacy-policy",
  "termsOfServiceUrl": "https://sampledex.com/terms-of-service",
  "githubUrl": "https://github.com/sampledex",
  "contactEmail": "contact@sampledex.com",
  "smartContractAddresses": {
    "mainnet": ["0x1234567890ABCDEF", "0x9876543210ABCDEF"],
    "testnet": ["0xA1B2C3D4E5F6", "0xFEDCBA0987654321"]
  },
  "enabled": true
}

=== Gelotto/ArchX-Wallet-Dapps/Archway-Dapps/Astrovault/details.json
{
  "name": "Astrovault",
  "description": "DeFi, Sustainably.",
  "dappImages": {
    "dappBanner": "axv-banner.png",
    "dappLogo": "axv-logo.png"
  },
  "websiteUrl": {
    "mainnet": "https://app.astrovault.io",
    "testnet": "https://wip.astrovault.io"
  },
  "category": [
    "DeFi-Decentralized Exchanges (DEX)",
    "DeFi-Yield Farming",
    "DeFi-Liquid Staking",
    "Infrastructure-Interoperability & Cross-Chain"
  ],
  "enabled": false
}

=== Gelotto/ArchX-Wallet-Dapps/Archway-Dapps/Liquid Finance/details.json
{
  "name": "Liquid Finance",
  "description": "Liquid Finance is a cutting-edge liquid staking protocol built on the Archway Network. It enables users to unlock the full potential of their staked assets, allowing for seamless trading, borrowing, and earning of yield without sacrificing staking rewards. With a focus on interoperability and scalability, Liquid Finance revolutionizes staking within the Archway ecosystem, offering a simple and secure solution for liquidity generation..",
  "dappImages": {
    "dappBanner": "liquid-finance-banner.jpg",
    "dappLogo": "liquid-finance-logo.jpg"
  },
  "websiteUrl": {
    "mainnet": "https://app.liquidfinance.xyz",
    "testnet": "https://test.liquidfinance.xyz"
  },
  "category": ["DeFi-Yield Farming", "DeFi-Liquid Staking"],
  "enabled": true
}
